---
name: Pulumi Kubernetes Operator Release
on:
  push:
    tags:
      - v*.*.*     # e.g. v2.0.0
      - v*.*-*.*   # e.g. v2.0-beta.1
env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_PASSWORD }}
          password: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            pulumi/pulumi-kubernetes-operator:${{ github.ref }}
          build-args: |
            VERSION=${VERSION}
  # release:
  #   runs-on: ubuntu-latest
  #   name: Tag Release
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2
  #     - name: Install Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.23.x
  #     - name: Login to Docker Hub
  #       run: |
  #         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  #     - name: Run GoReleaser
  #       uses: goreleaser/goreleaser-action@v6
  #       with:
  #         distribution: goreleaser
  #         version: '~> v2'
  #         args: release --clean
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
